### ISSUE TITLE
Can't override output template

### ISSUE THREAD

**Issue by sudsy** [soenneker/serilog-sinks-xunit-injectable#1]
First of all thanks for saving me a ton of time with my test debugging, I was really struggling to get logging from my asp.net fixture to appear in the correct place before I started using your tool.

One suggestion is that it would be great to be able to override the outpoutTemplate to include things like the source context. I can see that it could be done by changing the const output template to a property that the user can set, or as a parameter to the constructor of InjectableTestOutputSink. Happy to put in a PR for it, but I'm not sure how it would get published to nuget. Let me know what is the best path forward.

**Comment by soenneker** [comment]
Thanks @sudsy. The outputTemplate can now be set on the constructor of the sink.

As far as a PR goes, all you need to do is create a PR and once it's reviewed and merged the build pipeline will handle the rest of the NuGet deploy.
