### ISSUE TITLE
Is there a way to configure this from appsettings.json

### ISSUE THREAD

**Issue by mohamed-firoz** [soenneker/serilog-sinks-xunit-injectable#48]
Thanks for writing this application, really appreciated, documented very well.

I was wondering, if there is way to configure this from appsettings.json

I have a file "appsettings.Testing.json" for all my testing related settings.

so that my serilog code will read this.
`builder.Host.UseSerilog((context, services, configuration) => configuration
    .ReadFrom.Configuration(context.Configuration)
    .ReadFrom.Services(services)
);`

`"WriteTo": [
  {
    "Name": "InjectableTestOutputSink",
    "Args": {
      "restrictedToMinimumLevel": "Verbose",
      "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{SourceContext}] [{Level}] [InstanceId: {InstanceId}] [ReqId: {RequestId}] [CorrelationId: {CorrelationId}] {Message}{NewLine}{Exception}"
    }
  }
],`

Thanks.

**Comment by soenneker** [comment]
@mohamed-firoz Hi there, thanks for reaching out.

You're using [serilog-settings-configuration](https://github.com/serilog/serilog-settings-configuration) right?

I think it's possible to do some configuration of the sink via dynamic assembly loading in your appsettings.. I haven't tried it. You'd probably want to follow the assembly convention of `Serilog.Sinks.XUnit.Injectable`.

Most importantly is making sure that the sink is created as a singleton, and it's injected in the test though. Let me know how it goes.
